python benchmark_partition.py --npl 1 --npo 1
python benchmark_partition.py --npl 2 --npo 2
python benchmark_partition.py --npl 3 --npo 3
python benchmark_partition.py --npl 4 --npo 4
python benchmark_partition.py --npl 5 --npo 5
python benchmark_partition.py --npl 6 --npo 6
python benchmark_partition.py --npl 7 --npo 7
python benchmark_partition.py --npl 8 --npo 8
python benchmark_partition.py --npl 9 --npo 9
python benchmark_partition.py --npl 10 --npo 10
python benchmark_partition.py --npl 11 --npo 11
python benchmark_partition.py --npl 12 --npo 12
python benchmark_partition.py --npl 13 --npo 13
python benchmark_partition.py --npl 14 --npo 14
python benchmark_partition.py --npl 15 --npo 15
python benchmark_partition.py --npl 16 --npo 16
python benchmark_partition.py --npl 17 --npo 17
python benchmark_partition.py --npl 18 --npo 18
python benchmark_partition.py --npl 19 --npo 19
python benchmark_partition.py --npl 20 --npo 20
python benchmark_partition.py --npl 21 --npo 21
python benchmark_partition.py --npl 22 --npo 22
python benchmark_partition.py --npl 23 --npo 23
python benchmark_partition.py --npl 24 --npo 24
python benchmark_partition.py --npl 25 --npo 25
python benchmark_partition.py --npl 26 --npo 26
python benchmark_partition.py --npl 27 --npo 27
python benchmark_partition.py --npl 28 --npo 28
python benchmark_partition.py --npl 29 --npo 29
python benchmark_partition.py --npl 30 --npo 30
python benchmark_partition.py --npl 31 --npo 31
python benchmark_partition.py --npl 32 --npo 32
python benchmark_partition.py --npl 33 --npo 33
python benchmark_partition.py --npl 34 --npo 34
python benchmark_partition.py --npl 35 --npo 35
python benchmark_partition.py --npl 36 --npo 36
python benchmark_partition.py --npl 37 --npo 37
python benchmark_partition.py --npl 38 --npo 38
python benchmark_partition.py --npl 39 --npo 39
python benchmark_partition.py --npl 40 --npo 40
python benchmark_partition.py --npl 41 --npo 41
python benchmark_partition.py --npl 42 --npo 42
python benchmark_partition.py --npl 43 --npo 43
python benchmark_partition.py --npl 44 --npo 44
python benchmark_partition.py --npl 45 --npo 45
python benchmark_partition.py --npl 46 --npo 46
python benchmark_partition.py --npl 47 --npo 47
python benchmark_partition.py --npl 48 --npo 48
python benchmark_partition.py --npl 49 --npo 49
python benchmark_partition.py --npl 50 --npo 50
python benchmark_partition.py --npl 51 --npo 51
python benchmark_partition.py --npl 52 --npo 52
python benchmark_partition.py --npl 53 --npo 53
python benchmark_partition.py --npl 54 --npo 54
python benchmark_partition.py --npl 55 --npo 55
python benchmark_partition.py --npl 56 --npo 56
python benchmark_partition.py --npl 57 --npo 57
python benchmark_partition.py --npl 58 --npo 58
python benchmark_partition.py --npl 59 --npo 59
python benchmark_partition.py --npl 60 --npo 60
python benchmark_partition.py --npl 61 --npo 61
python benchmark_partition.py --npl 62 --npo 62
python benchmark_partition.py --npl 63 --npo 63
python benchmark_partition.py --npl 64 --npo 64
python benchmark_partition.py --npl 65 --npo 65
python benchmark_partition.py --npl 66 --npo 66
python benchmark_partition.py --npl 67 --npo 67
python benchmark_partition.py --npl 68 --npo 68
python benchmark_partition.py --npl 69 --npo 69
python benchmark_partition.py --npl 70 --npo 70
python benchmark_partition.py --npl 71 --npo 71
python benchmark_partition.py --npl 72 --npo 72
python benchmark_partition.py --npl 73 --npo 73
python benchmark_partition.py --npl 74 --npo 74
python benchmark_partition.py --npl 75 --npo 75
python benchmark_partition.py --npl 76 --npo 76
python benchmark_partition.py --npl 77 --npo 77
python benchmark_partition.py --npl 78 --npo 78
python benchmark_partition.py --npl 79 --npo 79
python benchmark_partition.py --npl 80 --npo 80
python benchmark_partition.py --npl 81 --npo 81
python benchmark_partition.py --npl 82 --npo 82
python benchmark_partition.py --npl 83 --npo 83
python benchmark_partition.py --npl 84 --npo 84
python benchmark_partition.py --npl 85 --npo 85
python benchmark_partition.py --npl 86 --npo 86
python benchmark_partition.py --npl 87 --npo 87
python benchmark_partition.py --npl 88 --npo 88
python benchmark_partition.py --npl 89 --npo 89
python benchmark_partition.py --npl 90 --npo 90
python benchmark_partition.py --npl 91 --npo 91
python benchmark_partition.py --npl 92 --npo 92
python benchmark_partition.py --npl 93 --npo 93
python benchmark_partition.py --npl 94 --npo 94
python benchmark_partition.py --npl 95 --npo 95
python benchmark_partition.py --npl 96 --npo 96
python benchmark_partition.py --npl 97 --npo 97
python benchmark_partition.py --npl 98 --npo 98
python benchmark_partition.py --npl 99 --npo 99
python benchmark_partition.py --npl 100 --npo 100
python benchmark_partition.py --npl 101 --npo 101
python benchmark_partition.py --npl 102 --npo 102
python benchmark_partition.py --npl 103 --npo 103
python benchmark_partition.py --npl 104 --npo 104
python benchmark_partition.py --npl 105 --npo 105
python benchmark_partition.py --npl 106 --npo 106
python benchmark_partition.py --npl 107 --npo 107
python benchmark_partition.py --npl 108 --npo 108
python benchmark_partition.py --npl 109 --npo 109
python benchmark_partition.py --npl 110 --npo 110
python benchmark_partition.py --npl 111 --npo 111
python benchmark_partition.py --npl 112 --npo 112
python benchmark_partition.py --npl 113 --npo 113
python benchmark_partition.py --npl 114 --npo 114
python benchmark_partition.py --npl 115 --npo 115
python benchmark_partition.py --npl 116 --npo 116
python benchmark_partition.py --npl 117 --npo 117
python benchmark_partition.py --npl 118 --npo 118
python benchmark_partition.py --npl 119 --npo 119
python benchmark_partition.py --npl 120 --npo 120
python benchmark_partition.py --npl 121 --npo 121
python benchmark_partition.py --npl 122 --npo 122
python benchmark_partition.py --npl 123 --npo 123
python benchmark_partition.py --npl 124 --npo 124
python benchmark_partition.py --npl 125 --npo 125
python benchmark_partition.py --npl 126 --npo 126
python benchmark_partition.py --npl 127 --npo 127
python benchmark_partition.py --npl 128 --npo 128
python benchmark_partition.py --npl 129 --npo 129
python benchmark_partition.py --npl 130 --npo 130
python benchmark_partition.py --npl 131 --npo 131
python benchmark_partition.py --npl 132 --npo 132
python benchmark_partition.py --npl 133 --npo 133
python benchmark_partition.py --npl 134 --npo 134
python benchmark_partition.py --npl 135 --npo 135
python benchmark_partition.py --npl 136 --npo 136
python benchmark_partition.py --npl 137 --npo 137
python benchmark_partition.py --npl 138 --npo 138
python benchmark_partition.py --npl 139 --npo 139
python benchmark_partition.py --npl 140 --npo 140
python benchmark_partition.py --npl 141 --npo 141
python benchmark_partition.py --npl 142 --npo 142
python benchmark_partition.py --npl 143 --npo 143
python benchmark_partition.py --npl 144 --npo 144
python benchmark_partition.py --npl 145 --npo 145
python benchmark_partition.py --npl 146 --npo 146
python benchmark_partition.py --npl 147 --npo 147
python benchmark_partition.py --npl 148 --npo 148
python benchmark_partition.py --npl 149 --npo 149
python benchmark_partition.py --npl 150 --npo 150
